function power_dot = generated_power(t,in2,I,mu,m,k_t,k_r,g,rho,L,W,h_0,F_r,F_t,w,b_r,b_t,nu,C_d)
%GENERATED_POWER
%    POWER_DOT = GENERATED_POWER(T,IN2,I,MU,M,K_T,K_R,G,RHO,L,W,H_0,F_R,F_T,W,B_R,B_T,NU,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Dec-2021 16:45:30

r = in2(:,1);
r_dot = in2(:,3);
theta = in2(:,2);
theta_dot = in2(:,4);
t2 = abs(r_dot);
t3 = cos(theta);
t4 = sin(theta);
t5 = I+mu;
t6 = t.*w;
t7 = W.^2;
t8 = h_0.^2;
t9 = r.^2;
t10 = rho.^2;
t11 = theta_dot.^2;
t13 = 1.0./m;
t12 = sin(t6);
t14 = 1.0./t5;
power_dot = k_r.*r_dot+k_t.*theta_dot-b_t.*(t14.*(-F_t.*t12+b_t.*theta_dot+k_t.*theta+nu.*theta_dot-(g.*m.*r.*t4)./2.0+(C_d.*W.*rho.*t8.^2.*theta_dot.*abs(theta_dot))./2.0)+1.0./t3.^3.*t14.*((L.*W.*g.*rho.*t8.*theta)./2.0+(L.*W.*g.*rho.*t3.*t4.*t8)./4.0-(L.*W.*g.*rho.*t3.^2.*t8.*theta)./4.0)-(g.*m.*r.*t3.*t14.*theta)./2.0)-b_r.*(-F_r.*t12.*t13+b_r.*r_dot.*t13-(g.*t4.*theta)./2.0+k_r.*r.*t13+(C_d.*W.*r_dot.^3.*rho.*t2)./4.0-(L.*W.*g.*h_0.*rho.*t13)./2.0+L.*W.*g.*h_0.*r.*rho.*t13-(C_d.*W.*k_t.*r_dot.*rho.*t2.*t13.*theta.^2)./4.0+(C_d.*I.*W.*r_dot.*rho.*t2.*t11.*t13)./4.0-(C_d.*W.*k_r.*r_dot.*rho.*t2.*t9.*t13)./4.0+(C_d.*W.*mu.*r_dot.*rho.*t2.*t11.*t13)./4.0+(C_d.*W.*g.*r.*r_dot.*rho.*t2.*t4.*theta)./4.0+(C_d.*L.*g.*h_0.*r.*r_dot.*t2.*t7.*t10.*t13)./4.0-(C_d.*L.*g.*h_0.*r_dot.*t2.*t7.*t9.*t10.*t13)./4.0+(C_d.*L.*g.*r_dot.*t2.*t4.*t7.*t8.*t10.*t13.*theta)./(t4.^2.*8.0-8.0));
