function q_ddot_sol = generated_accels(t,in2,mu,m,k_t,k_r,g,rho,L,W,h_0,F_r,F_t,w,b_r,b_t,nu,C_d)
%GENERATED_ACCELS
%    Q_DDOT_SOL = GENERATED_ACCELS(T,IN2,MU,M,K_T,K_R,G,RHO,L,W,H_0,F_R,F_T,W,B_R,B_T,NU,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Dec-2021 23:24:24

r = in2(:,1);
r_dot = in2(:,3);
theta = in2(:,2);
theta_dot = in2(:,4);
t2 = abs(r_dot);
t3 = cos(theta);
t4 = sin(theta);
t5 = t.*w;
t6 = W.^2;
t7 = h_0.^2;
t8 = mu.*3.0;
t9 = r.^2;
t10 = rho.^2;
t11 = theta_dot.^2;
t13 = 1.0./m;
t12 = sin(t5);
t14 = m.*t9.*4.0;
t15 = t8+t14;
t16 = 1.0./t15;
q_ddot_sol = [r.*t11.*(4.0./3.0)+F_r.*t12.*t13-b_r.*r_dot.*t13+(g.*t4.*theta)./2.0-k_r.*r.*t13-(C_d.*W.*r_dot.^3.*rho.*t2)./4.0+(L.*W.*g.*h_0.*rho.*t13)./2.0-L.*W.*g.*h_0.*r.*rho.*t13-(C_d.*W.*r_dot.*rho.*t2.*t9.*t11)./3.0+(C_d.*W.*k_t.*r_dot.*rho.*t2.*t13.*theta.^2)./4.0+(C_d.*W.*k_r.*r_dot.*rho.*t2.*t9.*t13)./4.0-(C_d.*W.*mu.*r_dot.*rho.*t2.*t11.*t13)./4.0-(C_d.*W.*g.*r.*r_dot.*rho.*t2.*t4.*theta)./4.0-(C_d.*L.*g.*h_0.*r.*r_dot.*t2.*t6.*t10.*t13)./4.0+(C_d.*L.*g.*h_0.*r_dot.*t2.*t6.*t9.*t10.*t13)./4.0-(C_d.*L.*g.*r_dot.*t2.*t4.*t6.*t7.*t10.*t13.*theta)./(t4.^2.*8.0-8.0);-t16.*(F_t.*t12.*-3.0+b_t.*theta_dot.*3.0+k_t.*theta.*3.0+nu.*theta_dot.*3.0-g.*m.*r.*t4.*(3.0./2.0)+m.*r.*r_dot.*theta_dot.*8.0+C_d.*W.*rho.*t7.^2.*theta_dot.*abs(theta_dot).*(3.0./2.0))-1.0./t3.^3.*t16.*(L.*W.*g.*rho.*t7.*theta.*(3.0./2.0)+L.*W.*g.*rho.*t3.*t4.*t7.*(3.0./4.0)-L.*W.*g.*rho.*t3.^2.*t7.*theta.*(3.0./4.0))+g.*m.*r.*t3.*t16.*theta.*(3.0./2.0)];
